export const LOCATION_SYNONYMS: Record<string, string> = {
  despensa: 'Despensa',
  dispensa: 'Despensa',
  pantry: 'Despensa',
  'garde manger': 'Despensa',
  'garde-manger': 'Despensa',
  placard: 'Despensa',
  closet: 'Despensa',
  armario: 'Despensa',
  alacena: 'Despensa',
  cupboard: 'Despensa',
  cabinet: 'Despensa',
  larder: 'Despensa',
  storage: 'Despensa',
  speisekammer: 'Despensa',
  vorratskammer: 'Despensa',
  despense: 'Despensa',
  nevera: 'Nevera',
  frigo: 'Nevera',
  refrigerador: 'Nevera',
  refrigerator: 'Nevera',
  fridge: 'Nevera',
  frigorifico: 'Nevera',
  frigorífico: 'Nevera',
  geladeira: 'Nevera',
  heladera: 'Nevera',
  frigidere: 'Nevera',
  frigerateur: 'Nevera',
  'réfrigérateur': 'Nevera',
  kühlschrank: 'Nevera',
  kuelschrank: 'Nevera',
  frigorifero: 'Nevera',
  cocina: 'Cocina',
  encimera: 'Cocina',
  counter: 'Cocina',
  countertop: 'Cocina',
  kitchen: 'Cocina',
  cuisine: 'Cocina',
  küche: 'Cocina',
  kuche: 'Cocina',
  cucina: 'Cocina',
  cozinha: 'Cocina',
  mesa: 'Cocina',
  table: 'Cocina',
  comedor: 'Cocina',
  congelador: 'Congelador',
  freezer: 'Congelador',
  'deep freezer': 'Congelador',
  congelatore: 'Congelador',
  'congelador portatil': 'Congelador',
  'congelador portátil': 'Congelador',
  congélateur: 'Congelador',
  gefrierschrank: 'Congelador',
  tiefkühler: 'Congelador',
  'congelador vertical': 'Congelador',
  congeladora: 'Congelador',
};
