export const APP_TIMING = {
  NEAR_EXPIRY_WINDOW_DAYS: 15,
  TOAST_DURATION: 1800,
} as const;

export const NEAR_EXPIRY_WINDOW_DAYS = APP_TIMING.NEAR_EXPIRY_WINDOW_DAYS;
export const TOAST_DURATION = APP_TIMING.TOAST_DURATION;
