import { addIcons } from 'ionicons';
import {
  add,
  addCircleOutline,
  addOutline,
  alarmOutline,
  alertCircle,
  alertCircleOutline,
  analyticsOutline,
  apertureOutline,
  appsOutline,
  archiveOutline,
  arrowForwardOutline,
  arrowUndoOutline,
  barChartOutline,
  basketOutline,
  bulbOutline,
  calendarOutline,
  cartOutline,
  checkmark,
  checkmarkCircle,
  checkmarkCircleOutline,
  checkmarkOutline,
  chevronDownOutline,
  chevronForwardOutline,
  chevronUpOutline,
  close,
  closeCircle,
  closeCircleOutline,
  closeOutline,
  createOutline,
  cubeOutline,
  desktopOutline,
  documentOutline,
  documentTextOutline,
  chatbubbleOutline,
  ellipse,
  ellipsisVerticalOutline,
  enterOutline,
  eyeOffOutline,
  eyeOutline,
  fastFoodOutline,
  filterOutline,
  homeOutline,
  hourglassOutline,
  imagesOutline,
  infinite,
  infiniteOutline,
  informationCircle,
  informationOutline,
  layersOutline,
  leafOutline,
  linkOutline,
  listOutline,
  lockClosedOutline,
  moonOutline,
  navigateOutline,
  notificationsOffOutline,
  notificationsOutline,
  paperPlaneOutline,
  pricetagOutline,
  receiptOutline,
  refreshOutline,
  reloadOutline,
  remove,
  removeCircleOutline,
  removeOutline,
  schoolOutline,
  searchOutline,
  sendOutline,
  settingsOutline,
  shareOutline,
  shareSocialOutline,
  shieldCheckmarkOutline,
  skullOutline,
  sparklesOutline,
  star,
  starOutline,
  statsChartOutline,
  storefrontOutline,
  sunnyOutline,
  timeOutline,
  toggleOutline,
  trashOutline,
  trendingDownOutline,
  trendingUpOutline,
  rocketOutline,
  warning,
  warningOutline,
  pencilOutline,
  pieChartOutline,
  fishOutline,
  nutritionOutline,
  pizzaOutline,
  iceCreamOutline,
  waterOutline,
  flaskOutline,
  ellipsisHorizontalOutline,
  helpCircleOutline,
} from 'ionicons/icons';

/**
 * Every Ionicon the app renders, registered once at bootstrap.
 *
 * Ionicons resolves names lazily at runtime, so an icon that is not registered
 * here renders as nothing and only warns in the console — which is why this
 * list lives in one findable place instead of scattered across components.
 *
 * Adding an icon means importing it and adding its kebab-case name below.
 */
export function registerAppIcons(): void {
  addIcons({
    // Food-type chips in the add row (FoodTypePickerComponent).
    'fish-outline': fishOutline,
    'nutrition-outline': nutritionOutline,
    'pizza-outline': pizzaOutline,
    'ice-cream-outline': iceCreamOutline,
    'water-outline': waterOutline,
    'flask-outline': flaskOutline,
    'ellipsis-horizontal-outline': ellipsisHorizontalOutline,
    'help-circle-outline': helpCircleOutline,
    add: add,
    remove: remove,
    close: close,
    star: star,
    checkmark: checkmark,
    infinite: infinite,
    ellipse: ellipse,
    'home-outline': homeOutline,
    'basket-outline': basketOutline,
    'cart-outline': cartOutline,
    'settings-outline': settingsOutline,
    'add-outline': addOutline,
    'add-circle-outline': addCircleOutline,
    'remove-outline': removeOutline,
    'trash-outline': trashOutline,
    'create-outline': createOutline,
    'receipt-outline': receiptOutline,
    'refresh-outline': refreshOutline,
    'chevron-up-outline': chevronUpOutline,
    'chevron-down-outline': chevronDownOutline,
    'filter-outline': filterOutline,
    'layers-outline': layersOutline,
    'alert-circle': alertCircle,
    'alert-circle-outline': alertCircleOutline,
    'hourglass-outline': hourglassOutline,
    'time-outline': timeOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'information-circle': informationCircle,
    'warning': warning,
    'link-outline': linkOutline,
    'list-outline': listOutline,
    'star-outline': starOutline,
    'pricetag-outline': pricetagOutline,
    'calendar-outline': calendarOutline,
    'cube-outline': cubeOutline,
    'fast-food-outline': fastFoodOutline,
    'enter-outline': enterOutline,
    'paper-plane-outline': paperPlaneOutline,
    'navigate-outline': navigateOutline,
    'storefront-outline': storefrontOutline,
    'ellipsis-vertical-outline': ellipsisVerticalOutline,
    'share-outline': shareOutline,
    'aperture-outline': apertureOutline,
    'sparkles-outline': sparklesOutline,
    'remove-circle-outline': removeCircleOutline,
    'sunny-outline': sunnyOutline,
    'moon-outline': moonOutline,
    'desktop-outline': desktopOutline,
    'chatbubble-outline': chatbubbleOutline,
    'document-outline': documentOutline,
    'document-text-outline': documentTextOutline,
    'close-outline': closeOutline,
    'arrow-forward-outline': arrowForwardOutline,
    'information-circle-outline': informationOutline,
    'notifications-outline': notificationsOutline,
    'skull-outline': skullOutline,
    'close-circle-outline': closeCircleOutline,
    'eye-outline': eyeOutline,
    'warning-outline': warningOutline,
    'close-circle': closeCircle,
    'stats-chart-outline': statsChartOutline,
    'share-social-outline': shareSocialOutline,
    'archive-outline': archiveOutline,
    'infinite-outline': infiniteOutline,
    'apps-outline': appsOutline,
    'leaf-outline': leafOutline,
    'eye-off-outline': eyeOffOutline,
    'arrow-undo-outline': arrowUndoOutline,
    'lock-closed-outline': lockClosedOutline,
    'analytics-outline': analyticsOutline,
    'bulb-outline': bulbOutline,
    'school-outline': schoolOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'trending-down-outline': trendingDownOutline,
    'trending-up-outline': trendingUpOutline,
    'rocket-outline': rocketOutline,
    'reload-outline': reloadOutline,
    'images-outline': imagesOutline,
    'bar-chart-outline': barChartOutline,
    'checkmark-outline': checkmarkOutline,
    'send-outline': sendOutline,
    'alarm-outline': alarmOutline,
    'search-outline': searchOutline,
    'notifications-off-outline': notificationsOffOutline,
    'toggle-outline': toggleOutline,
    'pencil-outline': pencilOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'pie-chart-outline': pieChartOutline
  });
}
